CANONICAL_FIELDS = [
    "ts", "host", "user", "src_ip", "dest_ip", "event_id", "channel", "process", "pid", "ppid", "parent_process",
    "command_line", "message", "target", "src_port", "dest_port", "protocol", "action", "bytes_sent", "bytes_recv",
    "url", "http_method", "http_status", "user_agent", "dns_query", "rule_name", "service_name", "registry_path",
    "file_path", "logon_type", "sender", "recipient", "subject", "duration",
    "ticket_encryption"
]

FIELD_LABELS = {
    "ts": "Vaqt",
    "host": "Xost / Qurilma",
    "user": "Foydalanuvchi",
    "src_ip": "Manba IP",
    "dest_ip": "Manzil IP",
    "event_id": "Hodisa ID",
    "channel": "Kanal / Manba",
    "process": "Jarayon",
    "pid": "PID",
    "ppid": "Ota PID",
    "parent_process": "Ota jarayon",
    "command_line": "Buyruq qatori",
    "message": "Xabar",
    "target": "Nishon",
    "src_port": "Manba porti",
    "dest_port": "Manzil porti",
    "protocol": "Protokol",
    "action": "Harakat",
    "bytes_sent": "Yuborilgan baytlar",
    "bytes_recv": "Qabul qilingan baytlar",
    "url": "URL",
    "http_method": "HTTP usuli",
    "http_status": "HTTP holati",
    "user_agent": "User-Agent",
    "dns_query": "DNS so'rovi",
    "rule_name": "Qoida nomi",
    "service_name": "Xizmat nomi",
    "registry_path": "Reestr yo'li",
    "file_path": "Fayl yo'li",
    "logon_type": "Tizimga kirish turi",
    "sender": "Yuboruvchi",
    "recipient": "Qabul qiluvchi",
    "subject": "Mavzu",
    "duration": "Davomiylik",
    "ticket_encryption": "Kerberos chipta shifri"
}
